// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckConflicts(paths: string[], destDir: string): $CancellablePromise<string[]> {
    return $Call.ByID(1244242588, paths, destDir).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CopyEntries(paths: string[], destDir: string, conflict: string): $CancellablePromise<$models.EntryOperationResult[]> {
    return $Call.ByID(2898335274, paths, destDir, conflict).then(($result: any) => {
        return $$createType2($result);
    });
}

export function CopyEntriesToTargets(pairs: $models.EntryPathPair[]): $CancellablePromise<$models.EntryOperationResult[]> {
    return $Call.ByID(2618535411, pairs).then(($result: any) => {
        return $$createType2($result);
    });
}

export function CreateFolder(parentDir: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(732689535, parentDir, name);
}

export function CreateFolderAt(path: string): $CancellablePromise<string> {
    return $Call.ByID(1281965482, path);
}

export function DeleteEmptyFolder(path: string): $CancellablePromise<string> {
    return $Call.ByID(1114495993, path);
}

export function DeleteEntries(paths: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(1689627624, paths).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetFileInfo(path: string): $CancellablePromise<$models.FileEntry> {
    return $Call.ByID(1693135863, path).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetHomeDir(): $CancellablePromise<string> {
    return $Call.ByID(4140196485);
}

export function GetRoots(): $CancellablePromise<$models.RootEntry[]> {
    return $Call.ByID(578700098).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetSeparator(): $CancellablePromise<string> {
    return $Call.ByID(400433148);
}

export function GetTrashInfo(): $CancellablePromise<$models.TrashInfo> {
    return $Call.ByID(3126279077).then(($result: any) => {
        return $$createType6($result);
    });
}

export function IsSameDrive(path1: string, path2: string): $CancellablePromise<boolean> {
    return $Call.ByID(2819228555, path1, path2);
}

export function ListDir(path: string): $CancellablePromise<$models.FileEntry[]> {
    return $Call.ByID(461256242, path).then(($result: any) => {
        return $$createType7($result);
    });
}

export function MoveEntries(paths: string[], destDir: string, conflict: string): $CancellablePromise<$models.EntryOperationResult[]> {
    return $Call.ByID(1201006282, paths, destDir, conflict).then(($result: any) => {
        return $$createType2($result);
    });
}

export function MoveEntriesToTargets(pairs: $models.EntryPathPair[]): $CancellablePromise<$models.EntryOperationResult[]> {
    return $Call.ByID(1863354771, pairs).then(($result: any) => {
        return $$createType2($result);
    });
}

export function OpenFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(975761513, path);
}

export function OpenInFileManager(path: string): $CancellablePromise<void> {
    return $Call.ByID(801103473, path);
}

export function OpenTerminal(path: string, terminalProgram: string): $CancellablePromise<void> {
    return $Call.ByID(2322032555, path, terminalProgram);
}

export function OpenTrash(): $CancellablePromise<void> {
    return $Call.ByID(2720739683);
}

export function OpenWithEditor(path: string, editorProgram: string): $CancellablePromise<void> {
    return $Call.ByID(569889906, path, editorProgram);
}

export function RenameEntry(path: string, name: string): $CancellablePromise<$models.FileEntry> {
    return $Call.ByID(1533604623, path, name).then(($result: any) => {
        return $$createType3($result);
    });
}

export function TrashEntries(paths: string[]): $CancellablePromise<$models.EntryOperationResult[]> {
    return $Call.ByID(238716349, paths).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.EntryOperationResult.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.FileEntry.createFrom;
const $$createType4 = $models.RootEntry.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.TrashInfo.createFrom;
const $$createType7 = $Create.Array($$createType3);
