// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService 是文件系统服务入口。mu/cacheOrder 供 ListDirPage 的分页枚举缓存使用。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AnalyzeSync compares source and target trees and returns the actions a
 * subsequent ExecuteSync would perform, without touching the filesystem.
 */
export function AnalyzeSync(config: $models.SyncConfig): $CancellablePromise<$models.SyncPlan | null> {
    return $Call.ByID(2493484506, config).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CheckConflicts(paths: string[], destDir: string): $CancellablePromise<string[]> {
    return $Call.ByID(1244242588, paths, destDir).then(($result: any) => {
        return $$createType2($result);
    });
}

export function CopyEntries(paths: string[], destDir: string, conflict: string): $CancellablePromise<$models.EntryOperationResult[]> {
    return $Call.ByID(2898335274, paths, destDir, conflict).then(($result: any) => {
        return $$createType4($result);
    });
}

export function CopyEntriesToTargets(pairs: $models.EntryPathPair[]): $CancellablePromise<$models.EntryOperationResult[]> {
    return $Call.ByID(2618535411, pairs).then(($result: any) => {
        return $$createType4($result);
    });
}

export function CreateFolder(parentDir: string, name: string): $CancellablePromise<string> {
    return $Call.ByID(732689535, parentDir, name);
}

export function CreateFolderAt(path: string): $CancellablePromise<string> {
    return $Call.ByID(1281965482, path);
}

export function DeleteEmptyFolder(path: string): $CancellablePromise<string> {
    return $Call.ByID(1114495993, path);
}

export function DeleteEntries(paths: string[]): $CancellablePromise<string[]> {
    return $Call.ByID(1689627624, paths).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ExecuteSync performs the synchronization described by config. It re-analyzes
 * the trees first so stale previews never cause unintended deletions. Items
 * failing mid-run are collected into SyncResult.Errors without aborting the
 * rest; only an invalid configuration or an unreachable source aborts early.
 */
export function ExecuteSync(config: $models.SyncConfig): $CancellablePromise<$models.SyncResult | null> {
    return $Call.ByID(1981589677, config).then(($result: any) => {
        return $$createType6($result);
    });
}

export function GetFileInfo(path: string): $CancellablePromise<$models.FileEntry> {
    return $Call.ByID(1693135863, path).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetFilePreview(path: string): $CancellablePromise<$models.FilePreview> {
    return $Call.ByID(4209707701, path).then(($result: any) => {
        return $$createType8($result);
    });
}

export function GetHomeDir(): $CancellablePromise<string> {
    return $Call.ByID(4140196485);
}

/**
 * GetInitialDir 返回应用启动时应该打开的目录。若通过命令行传入了有效目录则
 * 返回该目录，否则回退到 home 目录。
 */
export function GetInitialDir(): $CancellablePromise<string> {
    return $Call.ByID(287175394);
}

export function GetRoots(): $CancellablePromise<$models.RootEntry[]> {
    return $Call.ByID(578700098).then(($result: any) => {
        return $$createType10($result);
    });
}

export function GetSeparator(): $CancellablePromise<string> {
    return $Call.ByID(400433148);
}

export function GetTrashInfo(): $CancellablePromise<$models.TrashInfo> {
    return $Call.ByID(3126279077).then(($result: any) => {
        return $$createType11($result);
    });
}

export function IsSameDrive(path1: string, path2: string): $CancellablePromise<boolean> {
    return $Call.ByID(2819228555, path1, path2);
}

export function ListDir(path: string): $CancellablePromise<$models.FileEntry[]> {
    return $Call.ByID(461256242, path).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * ListDirPage 返回 path 目录的分页切片与总条数。
 *   - offset<0 与 limit<=0 归一化；limit 上限 5000（超界按上限截断）
 *   - offset 越界时返回空 entries 与正确 total
 *   - 条目在读取中途消失（Info() 失败）会被跳过但仍计入 total（与 ListDir 的 continue 语义一致）
 */
export function ListDirPage(path: string, offset: number, limit: number): $CancellablePromise<$models.DirPage> {
    return $Call.ByID(2813778809, path, offset, limit).then(($result: any) => {
        return $$createType13($result);
    });
}

export function MoveEntries(paths: string[], destDir: string, conflict: string): $CancellablePromise<$models.EntryOperationResult[]> {
    return $Call.ByID(1201006282, paths, destDir, conflict).then(($result: any) => {
        return $$createType4($result);
    });
}

export function MoveEntriesToTargets(pairs: $models.EntryPathPair[]): $CancellablePromise<$models.EntryOperationResult[]> {
    return $Call.ByID(1863354771, pairs).then(($result: any) => {
        return $$createType4($result);
    });
}

export function OpenFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(975761513, path);
}

export function OpenInFileManager(path: string): $CancellablePromise<void> {
    return $Call.ByID(801103473, path);
}

export function OpenTerminal(path: string, terminalProgram: string): $CancellablePromise<void> {
    return $Call.ByID(2322032555, path, terminalProgram);
}

export function OpenTrash(): $CancellablePromise<void> {
    return $Call.ByID(2720739683);
}

export function OpenWithEditor(path: string, editorProgram: string): $CancellablePromise<void> {
    return $Call.ByID(569889906, path, editorProgram);
}

export function RenameEntry(path: string, name: string): $CancellablePromise<$models.FileEntry> {
    return $Call.ByID(1533604623, path, name).then(($result: any) => {
        return $$createType7($result);
    });
}

export function SaveTextPreview(path: string, content: string, expectedVersion: string): $CancellablePromise<$models.FilePreview> {
    return $Call.ByID(840243591, path, content, expectedVersion).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * SetInitialDir 记录命令行参数指定的启动目录，供前端初始化定位。
 */
export function SetInitialDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(3541394886, dir);
}

export function TrashEntries(paths: string[]): $CancellablePromise<$models.EntryOperationResult[]> {
    return $Call.ByID(238716349, paths).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SyncPlan.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.EntryOperationResult.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.SyncResult.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.FileEntry.createFrom;
const $$createType8 = $models.FilePreview.createFrom;
const $$createType9 = $models.RootEntry.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.TrashInfo.createFrom;
const $$createType12 = $Create.Array($$createType7);
const $$createType13 = $models.DirPage.createFrom;
