// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class EntryOperationResult {
    "sourcePath": string;
    "targetPath": string;
    "skipped": boolean;
    "overwritten": boolean;

    /** Creates a new EntryOperationResult instance. */
    constructor($$source: Partial<EntryOperationResult> = {}) {
        if (!("sourcePath" in $$source)) {
            this["sourcePath"] = "";
        }
        if (!("targetPath" in $$source)) {
            this["targetPath"] = "";
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = false;
        }
        if (!("overwritten" in $$source)) {
            this["overwritten"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryOperationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): EntryOperationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EntryOperationResult($$parsedSource as Partial<EntryOperationResult>);
    }
}

export class EntryPathPair {
    "sourcePath": string;
    "targetPath": string;

    /** Creates a new EntryPathPair instance. */
    constructor($$source: Partial<EntryPathPair> = {}) {
        if (!("sourcePath" in $$source)) {
            this["sourcePath"] = "";
        }
        if (!("targetPath" in $$source)) {
            this["targetPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryPathPair instance from a string or object.
     */
    static createFrom($$source: any = {}): EntryPathPair {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EntryPathPair($$parsedSource as Partial<EntryPathPair>);
    }
}

export class FileEntry {
    "name": string;
    "path": string;
    "size": number;
    "modTime": time$0.Time;
    "isDir": boolean;
    "isHidden": boolean;
    "isSymlink": boolean;
    "linkTarget": string;
    "isExecutable": boolean;

    /** Creates a new FileEntry instance. */
    constructor($$source: Partial<FileEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = null;
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("isHidden" in $$source)) {
            this["isHidden"] = false;
        }
        if (!("isSymlink" in $$source)) {
            this["isSymlink"] = false;
        }
        if (!("linkTarget" in $$source)) {
            this["linkTarget"] = "";
        }
        if (!("isExecutable" in $$source)) {
            this["isExecutable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FileEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileEntry($$parsedSource as Partial<FileEntry>);
    }
}

export class FilePreview {
    "name": string;
    "path": string;
    "kind": string;
    "mimeType": string;
    "size": number;
    "version": string;
    "content": string;
    "dataUrl": string;
    "truncated": boolean;
    "message": string;

    /** Creates a new FilePreview instance. */
    constructor($$source: Partial<FilePreview> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("dataUrl" in $$source)) {
            this["dataUrl"] = "";
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilePreview instance from a string or object.
     */
    static createFrom($$source: any = {}): FilePreview {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FilePreview($$parsedSource as Partial<FilePreview>);
    }
}

export enum OperationKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OperationKindCopy = "copy",
    OperationKindMove = "move",
    OperationKindDelete = "delete",
    OperationKindTrash = "trash",
    OperationKindSync = "sync",
};

/**
 * OperationProgress is emitted to the frontend via the Wails event system
 * while a batch file operation is running.
 */
export class OperationProgress {
    "operationId": string;
    "kind": OperationKind;
    "phase": OperationProgressPhase;
    "totalItems": number;
    "doneItems": number;

    /**
     * -1 when unknown yet
     */
    "totalBytes": number;
    "doneBytes": number;
    "currentName": string;
    "error"?: string;

    /** Creates a new OperationProgress instance. */
    constructor($$source: Partial<OperationProgress> = {}) {
        if (!("operationId" in $$source)) {
            this["operationId"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = OperationKind.$zero;
        }
        if (!("phase" in $$source)) {
            this["phase"] = OperationProgressPhase.$zero;
        }
        if (!("totalItems" in $$source)) {
            this["totalItems"] = 0;
        }
        if (!("doneItems" in $$source)) {
            this["doneItems"] = 0;
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("doneBytes" in $$source)) {
            this["doneBytes"] = 0;
        }
        if (!("currentName" in $$source)) {
            this["currentName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OperationProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): OperationProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OperationProgress($$parsedSource as Partial<OperationProgress>);
    }
}

export enum OperationProgressPhase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OperationProgressPhaseScan = "scan",
    OperationProgressPhaseRun = "run",
    OperationProgressPhaseDone = "done",
    OperationProgressPhaseError = "error",
    OperationProgressPhaseCancelled = "cancelled",
};

export class RootEntry {
    "name": string;
    "path": string;
    "freeSpace": number;
    "totalSpace": number;

    /** Creates a new RootEntry instance. */
    constructor($$source: Partial<RootEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("freeSpace" in $$source)) {
            this["freeSpace"] = 0;
        }
        if (!("totalSpace" in $$source)) {
            this["totalSpace"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RootEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): RootEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RootEntry($$parsedSource as Partial<RootEntry>);
    }
}

export class SyncConfig {
    "sourceDir": string;
    "targetDir": string;

    /**
     * "mirror" | "incremental"
     */
    "mode": string;

    /**
     * 判重维度：文件大小
     */
    "compareSize": boolean;

    /**
     * 判重维度：修改时间
     */
    "compareModTime": boolean;

    /**
     * 判重维度：SHA-256 内容哈希
     */
    "compareHash": boolean;

    /**
     * 忽略隐藏文件
     */
    "ignoreHidden": boolean;

    /**
     * 名字精确匹配 + filepath.Match 通配符
     */
    "ignorePatterns": string[];

    /** Creates a new SyncConfig instance. */
    constructor($$source: Partial<SyncConfig> = {}) {
        if (!("sourceDir" in $$source)) {
            this["sourceDir"] = "";
        }
        if (!("targetDir" in $$source)) {
            this["targetDir"] = "";
        }
        if (!("mode" in $$source)) {
            this["mode"] = "";
        }
        if (!("compareSize" in $$source)) {
            this["compareSize"] = false;
        }
        if (!("compareModTime" in $$source)) {
            this["compareModTime"] = false;
        }
        if (!("compareHash" in $$source)) {
            this["compareHash"] = false;
        }
        if (!("ignoreHidden" in $$source)) {
            this["ignoreHidden"] = false;
        }
        if (!("ignorePatterns" in $$source)) {
            this["ignorePatterns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncConfig {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ignorePatterns" in $$parsedSource) {
            $$parsedSource["ignorePatterns"] = $$createField7_0($$parsedSource["ignorePatterns"]);
        }
        return new SyncConfig($$parsedSource as Partial<SyncConfig>);
    }
}

export class SyncCopyAction {
    "relPath": string;

    /**
     * 新增 | 大小不同 | 时间不同 | 内容不同 | 新增目录
     */
    "reason": string;

    /** Creates a new SyncCopyAction instance. */
    constructor($$source: Partial<SyncCopyAction> = {}) {
        if (!("relPath" in $$source)) {
            this["relPath"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncCopyAction instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncCopyAction {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncCopyAction($$parsedSource as Partial<SyncCopyAction>);
    }
}

export class SyncDeleteAction {
    "relPath": string;
    "isDir": boolean;

    /** Creates a new SyncDeleteAction instance. */
    constructor($$source: Partial<SyncDeleteAction> = {}) {
        if (!("relPath" in $$source)) {
            this["relPath"] = "";
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncDeleteAction instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncDeleteAction {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncDeleteAction($$parsedSource as Partial<SyncDeleteAction>);
    }
}

export class SyncItemError {
    "relPath": string;

    /**
     * analyze | copy | delete | cleanup
     */
    "op": string;
    "error": string;

    /** Creates a new SyncItemError instance. */
    constructor($$source: Partial<SyncItemError> = {}) {
        if (!("relPath" in $$source)) {
            this["relPath"] = "";
        }
        if (!("op" in $$source)) {
            this["op"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncItemError instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncItemError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SyncItemError($$parsedSource as Partial<SyncItemError>);
    }
}

export class SyncPlan {
    "copy": SyncCopyAction[];
    "delete": SyncDeleteAction[];
    "skippedCount": number;
    "errors": SyncItemError[];

    /** Creates a new SyncPlan instance. */
    constructor($$source: Partial<SyncPlan> = {}) {
        if (!("copy" in $$source)) {
            this["copy"] = [];
        }
        if (!("delete" in $$source)) {
            this["delete"] = [];
        }
        if (!("skippedCount" in $$source)) {
            this["skippedCount"] = 0;
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncPlan instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncPlan {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType4;
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("copy" in $$parsedSource) {
            $$parsedSource["copy"] = $$createField0_0($$parsedSource["copy"]);
        }
        if ("delete" in $$parsedSource) {
            $$parsedSource["delete"] = $$createField1_0($$parsedSource["delete"]);
        }
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField3_0($$parsedSource["errors"]);
        }
        return new SyncPlan($$parsedSource as Partial<SyncPlan>);
    }
}

export class SyncResult {
    /**
     * "done" | "cancelled"
     */
    "status": string;
    "copied": number;
    "deleted": number;
    "removedDirs": number;
    "skippedCount": number;
    "errors": SyncItemError[];

    /** Creates a new SyncResult instance. */
    constructor($$source: Partial<SyncResult> = {}) {
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("copied" in $$source)) {
            this["copied"] = 0;
        }
        if (!("deleted" in $$source)) {
            this["deleted"] = 0;
        }
        if (!("removedDirs" in $$source)) {
            this["removedDirs"] = 0;
        }
        if (!("skippedCount" in $$source)) {
            this["skippedCount"] = 0;
        }
        if (!("errors" in $$source)) {
            this["errors"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SyncResult instance from a string or object.
     */
    static createFrom($$source: any = {}): SyncResult {
        const $$createField5_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField5_0($$parsedSource["errors"]);
        }
        return new SyncResult($$parsedSource as Partial<SyncResult>);
    }
}

export class TrashInfo {
    "label": string;
    "path": string;
    "available": boolean;

    /** Creates a new TrashInfo instance. */
    constructor($$source: Partial<TrashInfo> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrashInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TrashInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrashInfo($$parsedSource as Partial<TrashInfo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = SyncCopyAction.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = SyncDeleteAction.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = SyncItemError.createFrom;
const $$createType6 = $Create.Array($$createType5);
