// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export class EntryOperationResult {
    "sourcePath": string;
    "targetPath": string;
    "skipped": boolean;
    "overwritten": boolean;

    /** Creates a new EntryOperationResult instance. */
    constructor($$source: Partial<EntryOperationResult> = {}) {
        if (!("sourcePath" in $$source)) {
            this["sourcePath"] = "";
        }
        if (!("targetPath" in $$source)) {
            this["targetPath"] = "";
        }
        if (!("skipped" in $$source)) {
            this["skipped"] = false;
        }
        if (!("overwritten" in $$source)) {
            this["overwritten"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryOperationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): EntryOperationResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EntryOperationResult($$parsedSource as Partial<EntryOperationResult>);
    }
}

export class EntryPathPair {
    "sourcePath": string;
    "targetPath": string;

    /** Creates a new EntryPathPair instance. */
    constructor($$source: Partial<EntryPathPair> = {}) {
        if (!("sourcePath" in $$source)) {
            this["sourcePath"] = "";
        }
        if (!("targetPath" in $$source)) {
            this["targetPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryPathPair instance from a string or object.
     */
    static createFrom($$source: any = {}): EntryPathPair {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EntryPathPair($$parsedSource as Partial<EntryPathPair>);
    }
}

export class FileEntry {
    "name": string;
    "path": string;
    "size": number;
    "modTime": time$0.Time;
    "isDir": boolean;
    "isHidden": boolean;
    "isSymlink": boolean;
    "linkTarget": string;
    "isExecutable": boolean;

    /** Creates a new FileEntry instance. */
    constructor($$source: Partial<FileEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = null;
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("isHidden" in $$source)) {
            this["isHidden"] = false;
        }
        if (!("isSymlink" in $$source)) {
            this["isSymlink"] = false;
        }
        if (!("linkTarget" in $$source)) {
            this["linkTarget"] = "";
        }
        if (!("isExecutable" in $$source)) {
            this["isExecutable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FileEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileEntry($$parsedSource as Partial<FileEntry>);
    }
}

export class FilePreview {
    "name": string;
    "path": string;
    "kind": string;
    "mimeType": string;
    "size": number;
    "version": string;
    "content": string;
    "dataUrl": string;
    "truncated": boolean;
    "message": string;

    /** Creates a new FilePreview instance. */
    constructor($$source: Partial<FilePreview> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("mimeType" in $$source)) {
            this["mimeType"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("dataUrl" in $$source)) {
            this["dataUrl"] = "";
        }
        if (!("truncated" in $$source)) {
            this["truncated"] = false;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilePreview instance from a string or object.
     */
    static createFrom($$source: any = {}): FilePreview {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FilePreview($$parsedSource as Partial<FilePreview>);
    }
}

export class RootEntry {
    "name": string;
    "path": string;
    "freeSpace": number;
    "totalSpace": number;

    /** Creates a new RootEntry instance. */
    constructor($$source: Partial<RootEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("freeSpace" in $$source)) {
            this["freeSpace"] = 0;
        }
        if (!("totalSpace" in $$source)) {
            this["totalSpace"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RootEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): RootEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RootEntry($$parsedSource as Partial<RootEntry>);
    }
}

export class TrashInfo {
    "label": string;
    "path": string;
    "available": boolean;

    /** Creates a new TrashInfo instance. */
    constructor($$source: Partial<TrashInfo> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrashInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): TrashInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrashInfo($$parsedSource as Partial<TrashInfo>);
    }
}
