// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Settings {
    "showHiddenFiles": boolean;
    "themeMode": string;
    "terminalProgram": string;
    "defaultEditor": string;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("showHiddenFiles" in $$source)) {
            this["showHiddenFiles"] = false;
        }
        if (!("themeMode" in $$source)) {
            this["themeMode"] = "";
        }
        if (!("terminalProgram" in $$source)) {
            this["terminalProgram"] = "";
        }
        if (!("defaultEditor" in $$source)) {
            this["defaultEditor"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}
