// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Settings {
    "showHiddenFiles": boolean;
    "themeMode": string;
    "terminalProgram": string;
    "defaultEditor": string;
    "pinnedQuickAccessPaths": string[];

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("showHiddenFiles" in $$source)) {
            this["showHiddenFiles"] = false;
        }
        if (!("themeMode" in $$source)) {
            this["themeMode"] = "";
        }
        if (!("terminalProgram" in $$source)) {
            this["terminalProgram"] = "";
        }
        if (!("defaultEditor" in $$source)) {
            this["defaultEditor"] = "";
        }
        if (!("pinnedQuickAccessPaths" in $$source)) {
            this["pinnedQuickAccessPaths"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pinnedQuickAccessPaths" in $$parsedSource) {
            $$parsedSource["pinnedQuickAccessPaths"] = $$createField4_0($$parsedSource["pinnedQuickAccessPaths"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
