// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddToContextMenu adds a Windows Explorer entry that opens selected folders
 * with the running application.
 */
export function AddToContextMenu(): $CancellablePromise<void> {
    return $Call.ByID(4075713172);
}

/**
 * AddToPath adds the running application to the current user's PATH and
 * updates the process environment immediately.
 */
export function AddToPath(): $CancellablePromise<void> {
    return $Call.ByID(44543575);
}

export function GetSettings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(489261139).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveSettings(settings: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(4168260778, settings);
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
