// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileTransferService 是暴露给前端（Wails binding）的文件剪贴板/拖拽服务。
 * 它委托给平台实现（darwin/windows/linux），前端只需调用 Copy/Cut/
 * ClipboardFiles/ClipboardSequence，无需感知平台差异。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearClipboard 清空系统剪贴板（剪切粘贴完成后消费剪切态）。
 */
export function ClearClipboard(): $CancellablePromise<void> {
    return $Call.ByID(1536114272);
}

/**
 * ClipboardFiles 返回系统剪贴板中的文件引用与操作语义。
 */
export function ClipboardFiles(): $CancellablePromise<$models.ClipboardContent> {
    return $Call.ByID(52178168).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ClipboardSequence 返回系统剪贴板变更序号，供前端判断剪贴板是否被外部改写。
 */
export function ClipboardSequence(): $CancellablePromise<number> {
    return $Call.ByID(1326489584);
}

/**
 * Copy 将 paths 指向的文件引用以复制语义写入系统剪贴板。
 */
export function Copy(paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(2017596488, paths);
}

/**
 * Cut 将 paths 指向的文件引用以移动语义写入系统剪贴板。
 */
export function Cut(paths: string[]): $CancellablePromise<void> {
    return $Call.ByID(2707357639, paths);
}

// Private type creation functions
const $$createType0 = $models.ClipboardContent.createFrom;
