// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ClipboardContent 是从系统剪贴板读取到的文件引用。
 */
export class ClipboardContent {
    "paths": string[];
    "op": ClipboardOperation;
    "seq": number;

    /** Creates a new ClipboardContent instance. */
    constructor($$source: Partial<ClipboardContent> = {}) {
        if (!("paths" in $$source)) {
            this["paths"] = [];
        }
        if (!("op" in $$source)) {
            this["op"] = ClipboardOperation.$zero;
        }
        if (!("seq" in $$source)) {
            this["seq"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClipboardContent instance from a string or object.
     */
    static createFrom($$source: any = {}): ClipboardContent {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField0_0($$parsedSource["paths"]);
        }
        return new ClipboardContent($$parsedSource as Partial<ClipboardContent>);
    }
}

/**
 * ClipboardOperation 表示写入系统剪贴板时文件引用的语义。
 */
export enum ClipboardOperation {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * ClipboardCopy 复制语义：目标粘贴后保留源文件。
     */
    ClipboardCopy = 0,

    /**
     * ClipboardMove 剪切/移动语义：目标粘贴后应删除源文件。
     */
    ClipboardMove = 1,
};

/**
 * DropEffect 表示拖拽操作允许的效果位（与 Windows DROPEFFECT / 调研定义一致）。
 */
export enum DropEffect {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    DropEffectCopy = 1,
    DropEffectMove = 2,
    DropEffectLink = 4,
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
