// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 是 Wails-facing 的流式文件服务器。Start 后 GetBaseURL 把
 * 含随机令牌的根地址暴露给前端，前端用 encodeAssetPath 兼容的
 * base64url 路径段拼接资源 URL。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * GetBaseURL 返回含令牌的流式根地址，例如
 * http://127.0.0.1:53101/media/<token>；服务器未启动时返回空串。
 */
export function GetBaseURL(): $CancellablePromise<string> {
    return $Call.ByID(1106956280);
}

/**
 * Start 绑定 127.0.0.1 的临时端口并在后台伺服。重复调用是幂等的。
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(684405158);
}

/**
 * Stop 关闭服务器（进行中的请求有 3 秒收尾时间）。
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(1568790158);
}
