// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetFileInfo(path: string): $CancellablePromise<$models.FileEntry> {
    return $Call.ByID(2925622295, path).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetHomeDir(): $CancellablePromise<string> {
    return $Call.ByID(3279025189);
}

export function GetSeparator(): $CancellablePromise<string> {
    return $Call.ByID(1235100380);
}

export function ListDir(path: string): $CancellablePromise<$models.FileEntry[]> {
    return $Call.ByID(168987282, path).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.FileEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
