// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CheckConflicts(paths: string[], destDir: string): $CancellablePromise<string[]> {
    return $Call.ByID(2845967612, paths, destDir).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CopyEntries(paths: string[], destDir: string, conflict: string): $CancellablePromise<void> {
    return $Call.ByID(3751035018, paths, destDir, conflict);
}

export function GetFileInfo(path: string): $CancellablePromise<$models.FileEntry> {
    return $Call.ByID(2925622295, path).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetHomeDir(): $CancellablePromise<string> {
    return $Call.ByID(3279025189);
}

export function GetRoots(): $CancellablePromise<$models.RootEntry[]> {
    return $Call.ByID(3710679330).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetSeparator(): $CancellablePromise<string> {
    return $Call.ByID(1235100380);
}

export function IsSameDrive(path1: string, path2: string): $CancellablePromise<boolean> {
    return $Call.ByID(491311531, path1, path2);
}

export function ListDir(path: string): $CancellablePromise<$models.FileEntry[]> {
    return $Call.ByID(168987282, path).then(($result: any) => {
        return $$createType4($result);
    });
}

export function MoveEntries(paths: string[], destDir: string, conflict: string): $CancellablePromise<void> {
    return $Call.ByID(2941554602, paths, destDir, conflict);
}

export function OpenFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(2444982985, path);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $models.FileEntry.createFrom;
const $$createType2 = $models.RootEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType1);
