// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../time/models.js";

export class FileEntry {
    "name": string;
    "path": string;
    "size": number;
    "modTime": time$0.Time;
    "isDir": boolean;
    "isHidden": boolean;

    /** Creates a new FileEntry instance. */
    constructor($$source: Partial<FileEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("modTime" in $$source)) {
            this["modTime"] = null;
        }
        if (!("isDir" in $$source)) {
            this["isDir"] = false;
        }
        if (!("isHidden" in $$source)) {
            this["isHidden"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): FileEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileEntry($$parsedSource as Partial<FileEntry>);
    }
}

export class RootEntry {
    "name": string;
    "path": string;
    "freeSpace": number;
    "totalSpace": number;

    /** Creates a new RootEntry instance. */
    constructor($$source: Partial<RootEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("freeSpace" in $$source)) {
            this["freeSpace"] = 0;
        }
        if (!("totalSpace" in $$source)) {
            this["totalSpace"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RootEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): RootEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RootEntry($$parsedSource as Partial<RootEntry>);
    }
}

export class Settings {
    "showHiddenFiles": boolean;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("showHiddenFiles" in $$source)) {
            this["showHiddenFiles"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}
