// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as filemanager$0 from "../../../../../zashiki/internal/filemanager/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "filemanager:operation-progress": filemanager$0.OperationProgress;
        }
    }
}
