// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LanShareService is the Wails-facing API of the LAN share feature: a lazy
 * HTTP workbench reachable from any browser on the local network.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFiles shares files or folders (folders are expanded recursively) and
 * lazily starts the server.
 */
export function AddFiles(paths: string[]): $CancellablePromise<$models.ShareItem[]> {
    return $Call.ByID(451424994, paths).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * AddText shares a text snippet.
 */
export function AddText(text: string): $CancellablePromise<$models.ShareItem> {
    return $Call.ByID(522435900, text).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ClearItems removes every shared item without stopping the server.
 */
export function ClearItems(): $CancellablePromise<void> {
    return $Call.ByID(2354590831);
}

/**
 * EnsureServer starts the share server if it is not running and returns the
 * current status including candidate URLs.
 */
export function EnsureServer(): $CancellablePromise<$models.ServerStatus> {
    return $Call.ByID(1067355257).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetPort returns the preferred port; the actual bound port may differ when
 * it was busy (see ServerStatus.Port).
 */
export function GetPort(): $CancellablePromise<number> {
    return $Call.ByID(3316292303);
}

/**
 * GetReceiveDir returns the directory browser uploads are saved into.
 */
export function GetReceiveDir(): $CancellablePromise<string> {
    return $Call.ByID(777220904);
}

/**
 * GetStatus reports the server state without starting it.
 */
export function GetStatus(): $CancellablePromise<$models.ServerStatus> {
    return $Call.ByID(3865711886).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * RemoveItem drops one shared item by ID; unknown IDs are ignored.
 */
export function RemoveItem(id: string): $CancellablePromise<void> {
    return $Call.ByID(3457221231, id);
}

/**
 * SetPort persists the preferred port and restarts a running server on it
 * (falling back to ephemeral when busy). Shared items survive the restart.
 */
export function SetPort(port: number): $CancellablePromise<void> {
    return $Call.ByID(874310499, port);
}

/**
 * SetReceiveDir validates and persists the upload target directory.
 */
export function SetReceiveDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(1851915748, dir);
}

/**
 * StopServer shuts the share server down and clears the share list.
 */
export function StopServer(): $CancellablePromise<void> {
    return $Call.ByID(2864280907);
}

// Private type creation functions
const $$createType0 = $models.ShareItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.ServerStatus.createFrom;
