// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ItemsChanged carries the full share list after any change.
 */
export class ItemsChanged {
    "items": ShareItem[];

    /** Creates a new ItemsChanged instance. */
    constructor($$source: Partial<ItemsChanged> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemsChanged instance from a string or object.
     */
    static createFrom($$source: any = {}): ItemsChanged {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new ItemsChanged($$parsedSource as Partial<ItemsChanged>);
    }
}

/**
 * ServerStatus describes the share server for the desktop UI.
 */
export class ServerStatus {
    "running": boolean;
    "port": number;
    "token"?: string;
    "urls": string[];
    "itemCount": number;

    /** Creates a new ServerStatus instance. */
    constructor($$source: Partial<ServerStatus> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("urls" in $$source)) {
            this["urls"] = [];
        }
        if (!("itemCount" in $$source)) {
            this["itemCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerStatus {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("urls" in $$parsedSource) {
            $$parsedSource["urls"] = $$createField3_0($$parsedSource["urls"]);
        }
        return new ServerStatus($$parsedSource as Partial<ServerStatus>);
    }
}

/**
 * ShareItem is one entry of the share list. It is delivered both to the
 * desktop UI and to the browser receiver page, therefore it must never
 * contain local paths: file downloads go through opaque IDs only.
 */
export class ShareItem {
    "id": string;
    "kind": ShareItemKind;
    "name": string;
    "size": number;
    "isImage"?: boolean;
    "mimeType"?: string;
    "text"?: string;
    "addedAt": string;

    /** Creates a new ShareItem instance. */
    constructor($$source: Partial<ShareItem> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = ShareItemKind.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            this["size"] = 0;
        }
        if (!("addedAt" in $$source)) {
            this["addedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ShareItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ShareItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ShareItem($$parsedSource as Partial<ShareItem>);
    }
}

/**
 * ShareItemKind marks the type of a shared item.
 */
export enum ShareItemKind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ShareItemKindFile = "file",
    ShareItemKindText = "text",
};

/**
 * TextReceived is emitted when a browser sends a text message to Zashiki.
 */
export class TextReceived {
    "id": string;
    "text": string;
    "remoteAddr": string;
    "at": string;

    /** Creates a new TextReceived instance. */
    constructor($$source: Partial<TextReceived> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("remoteAddr" in $$source)) {
            this["remoteAddr"] = "";
        }
        if (!("at" in $$source)) {
            this["at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TextReceived instance from a string or object.
     */
    static createFrom($$source: any = {}): TextReceived {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TextReceived($$parsedSource as Partial<TextReceived>);
    }
}

/**
 * TransferDirection marks whether a transfer is a browser pulling a shared
 * file (download) or a browser pushing a file to Zashiki (upload).
 */
export enum TransferDirection {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TransferDirectionDownload = "download",
    TransferDirectionUpload = "upload",
};

/**
 * TransferProgress is emitted to the desktop UI while a browser is
 * downloading shared files or uploading files to Zashiki.
 */
export class TransferProgress {
    "transferId": string;
    "direction": TransferDirection;
    "remoteAddr": string;
    "name": string;

    /**
     * -1 when unknown
     */
    "totalBytes": number;
    "doneBytes": number;
    "phase": TransferProgressPhase;
    "error"?: string;

    /** Creates a new TransferProgress instance. */
    constructor($$source: Partial<TransferProgress> = {}) {
        if (!("transferId" in $$source)) {
            this["transferId"] = "";
        }
        if (!("direction" in $$source)) {
            this["direction"] = TransferDirection.$zero;
        }
        if (!("remoteAddr" in $$source)) {
            this["remoteAddr"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("totalBytes" in $$source)) {
            this["totalBytes"] = 0;
        }
        if (!("doneBytes" in $$source)) {
            this["doneBytes"] = 0;
        }
        if (!("phase" in $$source)) {
            this["phase"] = TransferProgressPhase.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TransferProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): TransferProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TransferProgress($$parsedSource as Partial<TransferProgress>);
    }
}

/**
 * TransferProgressPhase is the lifecycle phase of a single transfer.
 */
export enum TransferProgressPhase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TransferPhaseRun = "run",
    TransferPhaseDone = "done",
    TransferPhaseError = "error",
};

// Private type creation functions
const $$createType0 = ShareItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
